# -*- coding: utf-8 -*-
"""assignment 1 lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4gX32rofPJTsPxP9g5aUs1yPylAuIsU
"""

T= int(input(""))
for i in range(T):
  n= int(input(""))
  if n%2==0:
    print(f"{n} is an Even number.")
  else:
    print(f"{n} is an Odd number.")

T= int(input(""))
st1=[]
st2=[]
for i in range(T):
  str1=input("")
  a= str1.split()
  for j in range(len(a)):
    if a[j].isdigit():
      st1.append(int(a[j]))
    if a[j]=="+" or a[j]=="-" or a[j]=="/" or a[j]=="*":
        st2.append(a[j])
  if len(st1)>=2 and st2:
    num2 = st1.pop()
    num1=st1.pop()
    op= st2.pop()
    if op=="+":
       print(round(float(num1+num2),6))
    if op=="-":
       print(round(float(num1-num2),6))
    if op=="/":
       print(round(float(num1/num2),6))
    if op=="*":
      print(round(float(num1*num2),6))

N,K = input().split()
N,K = int(N), int(K)



arr1=input().split()
arr1=[int(x) for x in arr1]
arr1=arr1[::-1]

for i in range(N-K,N):
  print(arr1[i], end=" ")

T = int(input())
for i in range(T):
  N= int(input())
  print(int(N*(N+1)/2))

T= int(input())
arr1= input().split()
arr1=[int(x) for x in arr1]
sort_needed= True
for i in range(len(arr1)-1):

   if not sort_needed:
     break
   sort_needed=False
   for j in range(len(arr1)-i-1):
    if arr1[j]>arr1[j+1]:
      arr1[j],arr1[j+1]=arr1[j+1],arr1[j]
      sort_needed=True
print(*arr1)

T= int(input())
ID= input().split()
ID= [int(x) for x in ID]
marks= input().split()
marks= [int(y) for y in marks]
swap=0
whole=[]

for i in range(T):
  whole.append((ID[i],marks[i]))
for i in range(T):
  maxidx=i
  for j in range(i+1,T):
    if whole[j][1]> whole[maxidx][1]:
       maxidx=j
    elif whole[maxidx][1]==whole[j][1] and whole[j][0]< whole[maxidx][0]:
       maxidx=j
  if maxidx!=i:
    whole[i], whole[maxidx]= whole[maxidx], whole[i]
    swap+=1

print(f"Minimum swaps: {swap}")
for student in whole:
  print(f"ID: {student[0]} Mark: {student[1]}")

T = int(input())
whole=[]
for i in range(T):
  line=input()
  a= line.split()
                                             ##################MAINNNNNNNNNNNNNNNNNNNN
  x=a[0]
  hehe=a[len(a)-1]
  y,o= hehe.split(":")
  y=int(y)
  whole.append((x,y,line))
for i in range(T):
   for j in range(i+1,T):
    if whole[i][0][0]>whole[j][0][0]:
      whole[i], whole[j]=whole[j], whole[i]
    elif whole[i][0][0]==whole[j][0][0] and whole[i][0]>whole[j][0] :
      whole[i], whole[j]=whole[j], whole[i]
    elif whole[i][0]==whole[j][0] and whole[i][1]<whole[j][1]:

      whole[i], whole[j]=whole[j], whole[i]
for train in whole:
  print(train[2])